[supervisord]
nodaemon=true
user=monad
logfile=/home/monad/supervisord.log
pidfile=/home/monad/supervisord.pid

[program:monad-bft]
command=/usr/bin/monad-bft
directory=/home/monad
autostart=true
autorestart=true
stderr_logfile=/home/monad/monad-bft-stderr.log
stdout_logfile=/home/monad/monad-bft-stdout.log
stopwaitsecs=300
stopsignal=TERM

[program:monad-execution]
command=/usr/bin/monad-execution %(ENV_EXECUTION_EXTRA_FLAGS)s
directory=/home/monad
autostart=true
autorestart=true
stderr_logfile=/home/monad/monad-execution-stderr.log
stdout_logfile=/home/monad/monad-execution-stdout.log
stopwaitsecs=300
stopsignal=TERM

[program:monad-rpc]
command=/usr/bin/monad-rpc
directory=/home/monad
autostart=true
autorestart=true
stderr_logfile=/home/monad/monad-rpc-stderr.log
stdout_logfile=/home/monad/monad-rpc-stdout.log
stopwaitsecs=300
stopsignal=TERM
